### ISSUE TITLE
Desired feature: ability to configure target utilization

### ISSUE THREAD

**Issue by TehShrike** [Signiant/dynamodb-autoscale-enabler#1]
First: I'm glad I found this script - the AWS API is pretty annoying when it comes to autoscaling!

If I'm reading [the code](https://github.com/Signiant/dynamodb-autoscale-enabler/blob/3e5f7f0418deb9434c29ebfcbb27e89e1d6db08a/autoscale-toggle.sh#L202) correctly, it looks like the script is currently hardcoded to set target utilization to 50%.

This seems more sensible than the default of 70%, but I'd still like to be able to tweak that number - are you open to adding an argument to allow setting custom values?

**Comment by dnorth98** [comment]
Makes total sense.  I've added a new `-u` flag to allow you to specify the target utilization.  It sets the same value for read and write as it did before but now it's a parameter.

**Comment by TehShrike** [comment]
Awesome, thanks so much!
